spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #这里是配置注册中心的地址，而bootstrap.properties中配置的是配置中心的地址
  application:
    name: gulimall-third-party
server:
  port: 30000
alibaba:
  cloud:
    access-key: #你的alibaba云存储access-key
    secret-key: #你的alibaba云存储secret-key
    oss:
      endpoint: #你的alibaba云存储端点信息
      bucket: #存储空间名称
